const Router = require('express')
const router = new Router()
const teacherRoutes = require('./teacherRoutes')
const studentRoutes = require('./studentRoutes')
const disciplineRoutes = require('./disciplineRoutes')
const lessonRoutes = require('./lessonRoutes')
const typeRoutes = require('./typeRoutes')
const scheduleRoutes = require('./scheduleRoutes')
const timetableRoutes = require('./timetableRoutes')
const teacherlessonRoutes = require('./teacherlessonRoutes')
const studentsDisciplinesRoutes = require('./studentsDisciplinesRoutes')

router.use('/student', studentRoutes)
router.use('/teacher', teacherRoutes)
router.use('/discipline', disciplineRoutes)
router.use('/lesson', lessonRoutes)
router.use('/type', typeRoutes)
router.use('/timetable', timetableRoutes)
router.use('/schedule', scheduleRoutes)
router.use('/teacherlesson', teacherlessonRoutes)
router.use('/studentDiscipline', studentsDisciplinesRoutes)

module.exports = router