export const SCHEDULE_ROUTE = '/'
export const TEACHER_ROUTE = '/teacher'
export const STUDENT_ROUTE = '/student'
export const DISCIPLINE_ROUTE = '/discipline'
export const ELECTIVE_ROUTE = '/elective'